### PR TITLE
license: re-license Project ImmortalWrt under GPL-2.0-only

### PR DESCRIPTION
**Pull request by 1715173329**
This fixes license conflicting with upstream OpenWrt.

The ImmortalWrt project was born from [coolsnowwolf/lede](https://github.com/coolsnowwolf/lede), which is a Chinese fork of OpenWrt.
@coolsnowwolf licensed some of his packages under GPL-3.0-only, so when I created this project, I chose the same license for the project license. However, this is wrong.
Now most of those packages have been moved into `luci`/`packages` feed, it's time to address this problem, before we getting into real trouble.

All dear contributors, please tell me if you are okay with this change.
Note, this change will be applied to all branches.
To: @immortalwrt
To: @immortalwrt/developers
To: @immortalwrt/maintainers
Cc: @aiamadeus
Cc: @alk3pInjection 
Cc: @Beginner-Go 
Cc: @EdiTurn 
Cc: @eltociear 
Cc: @EnnawYang 
Cc: @HoldOnBro 
Cc: @hue715 
Cc: @kiddin9 
Cc: @Mattraks
Cc: @MkQtS 
Cc: @padavanonly
Cc: @skbeh 
Cc: @stupidloud 
Cc: @SuLingGG 
Cc: @xlighting2017
Cc: @zcluo
Cc: @zheshifandian
Cc: @zgc
Cc: @zxlhhyccc

### CODE REVIEW

**Comment by EnnawYang** [comment]
okay

**Comment by zheshifandian** [comment]
okey

**Comment by eltociear** [comment]
👌

**Comment by skbeh** [comment]
No problem.

**Comment by hue715** [comment]
👌

**Comment by Beginner-Go** [comment]
okay

**Comment by SuLingGG** [comment]
Okay~

**Comment by zgc** [comment]
okay

**Comment by 1715173329** [comment]
Merged, thank you!

**Pull request merged**
