### PR TITLE
[18.06-dev] v2ray-core: update to 4.37.3

### PR DESCRIPTION
**Pull request by Beginner-Go**

### CODE REVIEW

**Comment by 1715173329** [comment]
What happened to #357?

**Comment by Beginner-Go** [comment]
> What happened to #357?

https://github.com/immortalwrt/immortalwrt/pull/323#issuecomment-800385825

**Comment by 1715173329** [comment]
> [#323 (comment)](https://github.com/immortalwrt/immortalwrt/pull/323#issuecomment-800385825)

Just... use edit...
image

**Comment by 1715173329** [comment]
Merged, thanks for PR.

**Pull request merged**
