### PR TITLE
wolfssl: fix /dev/crytpo:build failed

### PR DESCRIPTION
**Pull request by zxlhhyccc**
build failed when compiling the option with /dev/crytpo

### CODE REVIEW

**Comment by AmadeusGhost** [comment]
真有问题的话麻烦发到官方那边。。。

**Comment by zxlhhyccc** [comment]
> 真有问题的话麻烦发到官方那边。。。

不打这个补丁确实是有问题的，编译报错。。。。
image

**Comment by 1715173329** [comment]
Please use upstream patch instead of your own copy.
https://github.com/wolfSSL/wolfssl/commit/096889927d9528d4fbeb3aab56d1fe8225d2e7ec

**Comment by zxlhhyccc** [comment]
> Please use upstream patch instead of your own copy. [wolfSSL/wolfssl@0968899](https://github.com/wolfSSL/wolfssl/commit/096889927d9528d4fbeb3aab56d1fe8225d2e7ec)

好的，我的失误，我没去看wolfssl官方。。。

**Pull request closed without merging**
