### PR TITLE
Add support for HiWiFi R33, fix 'eth0 transmit timed out' for mt7620 switch.

### PR DESCRIPTION
**Pull request by Kissycat**
添加由zfdx123提供的对极路由3 Pro（HiWiFi R33 | C312B)的支持，跟进上游openwrt的mtk交换机驱动以修复MT7620的大流量断流问题。

### CODE REVIEW

**Comment by 1715173329** [comment]
support for the 18.06 branch is EoL.

**Comment by Kissycat** [comment]
> support for the 18.06 branch is EoL.

啊这，可是这机子在kernel 5.10测试无法启动来着，只能进5.4的18.06...

**Comment by zfdx123** [comment]
@1715173329 The reason for not being able to boot is that there is no NAND driver. He has not submitted the driver. I will submit it when I finish the work at hand.

**Comment by 1715173329** [comment]
@zfdx123 hello, the 18.06 series are deprecated and no longer accept any updates .

**Comment by zfdx123** [comment]
> 

I will merge the latest branch.

**Comment by zfdx123** [comment]
@1715173329 I'll merge master.

**Comment by 1715173329** [comment]
21.02 is preferred, as I don't wanna maintain hacks on snapshot branch (iirc the mt7620 nand driver was rejected by upstream).

**Comment by zfdx123** [comment]
> 21.02 is preferred, as I don't wanna maintain hacks on snapshot branch (iirc the mt7620 nand driver was rejected by upstream).

nand似乎在呗ptpt52维护，但是并不能确定维护周期，那我会在出现完整nand时提交

**Comment by Kissycat** [comment]
> nand

原来是nand驱动的问题嘛，我看到lede那有人说是有些机子启动不了5.10，lean才把ramip的默认内核切回5.4，合着同一分支不同内核启用的驱动还不一样。

害我昨天在18.04编译了半天最新软件包，得，今天冲21.x去了...

**Comment by zfdx123** [comment]
> nand

lean的nand驱动是以patch的驱动存在的在patch-5.4文件夹里，ptpt52的nand应该是可以兼容到5.15但是，lean似乎并没有copy驱动

**Comment by Kissycat** [comment]
> 5.15

好嘛，那今天直接上immortal的5.15😂

说起来，我之前测试5.4的lede，发现lede开启硬件加速后，无线还是跑不到200M，而同5.4，18.06的immortal是可以稳300M的，都是闭源mtk驱动.

**Comment by zfdx123** [comment]
> ImmortalWrt

感觉与lean相比更喜欢ImmortalWrt，虽然使用少但是在稳定性上应该是可以的

**Pull request closed without merging**
